"""
Plot mean ILP entropy by letter position with drop-coded lines and
separate panes for word lengths 4 through 9.

The script expects a `results.csv` produced by `scripts/main.py` in the
supplied run directory. It saves `mean_entropy_by_length.png` (300 dpi).
"""
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


def load_results(run_directory: Path) -> pd.DataFrame:
    csv_path = run_directory / "results.csv"
    if not csv_path.exists():
        raise FileNotFoundError(f"results.csv not found in {run_directory}")

    df = pd.read_csv(csv_path)
    required = {"word", "drop_left", "drop_right", "pos", "entropy"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Missing columns in results.csv: {', '.join(sorted(missing))}")

    df["length"] = df["word"].str.len()
    df = df[df["length"].between(4, 9)]
    if df.empty:
        raise ValueError("No words with lengths 4-9 available for plotting.")

    df["drop"] = ((df["drop_left"] + df["drop_right"]) / 2).round(3)
    df["pos"] = df["pos"].astype(int)
    return df


def build_plot(df: pd.DataFrame, run_directory: Path) -> None:
    sns.set_theme(style="whitegrid", context="talk")

    agg = (
        df.groupby(["length", "pos", "drop"])["entropy"]
        .mean()
        .reset_index()
        .sort_values(["length", "drop", "pos"])
    )

    palette = sns.color_palette("mako", n_colors=agg["drop"].nunique())
    g = sns.FacetGrid(
        agg,
        col="length",
        col_wrap=3,
        hue="drop",
        palette=palette,
        sharex=False,  # free x-axis scale per length
        sharey=True,
        height=3.8,
        aspect=1.3,
        legend_out=False,
        margin_titles=True,
    )
    g.map_dataframe(sns.lineplot, x="pos", y="entropy", linewidth=2.4, alpha=0.92)
    g.set_axis_labels("Letter position", "Mean entropy (bits)")
    g.set_titles("Length {col_name}", fontweight="semibold")

    for ax in g.axes.flatten():
        if ax is None:
            continue
        ax.set_ylim(bottom=0)
        ax.grid(True, which="major", linewidth=0.4, color="#d0d3e0")
        ax.set_facecolor("#f8f9fc")

    g.figure.suptitle("Mean ILP Entropy by Position and Drop", fontsize=18, fontweight="bold")

    handles, labels = g.axes[0].get_legend_handles_labels()
    if handles:
        formatted = [f"{float(lbl):.2f}" for lbl in labels]
        unique = dict()
        for label, handle in zip(formatted, handles):
            unique[label] = handle
        ordered_labels = sorted(unique.keys(), key=float)
        ordered_handles = [unique[label] for label in ordered_labels]
        g.figure.legend(
            ordered_handles,
            ordered_labels,
            title="Drop",
            loc="center right",
            frameon=True,
            borderaxespad=0.6,
            borderpad=0.7,
            fontsize=11,
            title_fontsize=12,
        )

    g.figure.tight_layout(rect=(0, 0, 0.92, 0.96))

    png_path = run_directory / "mean_entropy_by_length.png"
    g.figure.savefig(png_path, dpi=300, bbox_inches="tight")
    print(f"Saved {png_path.name} to {run_directory}")
    plt.close(g.figure)


def main(run_directory: str) -> None:
    run_dir = Path(run_directory)
    df = load_results(run_dir)
    build_plot(df, run_dir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "run_directory",
        type=str,
        help="Directory containing results.csv generated by scripts/main.py.",
    )
    args = parser.parse_args()
    main(args.run_directory)
